version: "3.4"

services:
  # 注册中心
  eureka:
    image: registry.cn-hangzhou.aliyuncs.com/cloud_oj/register-center:latest
    deploy:
      resources:
        limits:
          memory: 1024M
      placement:
        constraints:
          - node.role == manager
    networks:
      - oj-net
    ports:
      - target: 8761
        published: 8761
        mode: ingress
    volumes:
      - "log:/app/log"

  # 服务监控
  monitor_service:
    image: registry.cn-hangzhou.aliyuncs.com/cloud_oj/monitor-service:latest
    deploy:
      resources:
        limits:
          memory: 1024M
      placement:
        constraints:
          - node.role == manager
    networks:
      - oj-net
    ports:
      - target: 5000
        published: 5000
        mode: ingress
    volumes:
      - "log:/app/log"
    environment:
      EUREKA_SERVER: "eureka:8761"

  # 路由网关
  api_gateway:
    image: registry.cn-hangzhou.aliyuncs.com/cloud_oj/api-gateway:latest
    deploy:
      resources:
        limits:
          memory: 1024M
      placement:
        constraints:
          - node.role == manager
    networks:
      - oj-net
    ports:
      - target: 80
        published: 80
        mode: ingress
    volumes:
      - "log:/app/log"
    environment:
      EUREKA_SERVER: "eureka:8761"
      MYSQL_URL: "jdbc:mysql://mysql:3306/cloud_oj"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "cloud"
      DB_POOL_SIZE: 12

  # Web
  oj_web:
    image: registry.cn-hangzhou.aliyuncs.com/cloud_oj/web:latest
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 1024M
      placement:
        constraints:
          - node.role == worker
    networks:
      - oj-net
    environment:
      API_HOST: "gateway"

  # 管理服务
  manager_service:
    image: registry.cn-hangzhou.aliyuncs.com/cloudli/manager-service:latest
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 2048M
      placement:
        constraints:
          - node.role == worker
    networks:
      - oj-net
    volumes:
      - "oj_file:/oj_file"
      - "log:/app/log"
    environment:
      EUREKA_SERVER: "eureka:8761"
      MYSQL_URL: "jdbc:mysql://mysql:3306/cloud_oj?allowMultiQueries=true"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "cloud"
      DB_POOL_SIZE: 12

  # 文件服务
  file_server:
    image: registry.cn-hangzhou.aliyuncs.com/cloudli/file-server:latest
    user: "1000"    # 指定 uid
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 1024M
      placement:
        constraints:
          - node.role == worker
    networks:
      - oj-net
    volumes:
      - "oj_file:/oj_file"
      - "log:/app/log"
    environment:
      EUREKA_SERVER: "eureka:8761"

  # 判题服务
  judge_service:
    image: registry.cn-hangzhou.aliyuncs.com/cloudli/judge-service:latest
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 3072M
      placement:
        constraints:
          - node.role == worker
    networks:
      - oj-net
    volumes:
      - "oj_file:/oj_file"
      - "target:/target"
      - "log:/app/log"
    environment:
      EUREKA_SERVER: "eureka:8761"
      MYSQL_URL: "jdbc:mysql://mysql:3306/cloud_oj"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "cloud"
      DB_POOL_SIZE: 12
      RABBIT_URL: "rabbitmq"
      RABBIT_PORT: "5672"
      RABBIT_USER: "cloud@oj"
      RABBIT_PASSWORD: "cloud@oj"
      CORE_POOL_SIZE: 8
      MAX_POOL_SIZE: 16
      QUEUE_CAPACITY: 200

  # 数据库
  mysql:
    image: mysql:8.0.18
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - oj-net
    ports:
      - "3306:3306"
    configs:
      - source: mysql_config
        target: /etc/mysql/conf.d/my.cnf
      - source: init_sql
        target: /docker-entrypoint-initdb.d/init_cloud_oj.sql
    volumes:
      - "mysql:/var/lib/mysql"    # 数据目录
    environment:
      MYSQL_ROOT_PASSWORD: "cloud"
      MYSQL_ROOT_HOST: "%"

  # 消息队列
  rabbitmq:
    image: rabbitmq:3.8.2-management
    deploy:
      placement:
        constraints:
          - node.role == manager
    hostname: rabbitmq
    networks:
      - oj-net
    environment:
      RABBITMQ_DEFAULT_USER: "cloud@oj"
      RABBITMQ_DEFAULT_PASS: "cloud@oj"
    ports:
      - "15672:15672"
    volumes:
      - "rabbit:/var/lib/rabbitmq/mnesia"

configs:
  mysql_config:
    file: ./mysql/config/my.cnf           # mysql 配置文件
  init_sql:
    file: ./mysql/sql/init_cloud_oj.sql   # 数据库初始化脚本

networks:
  oj-net:
    driver: overlay
    ipam:
      config:
        - subnet: 10.16.0.0/16

volumes:
  mysql:
  rabbit:
  target:
  log:
  oj_file:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.3,rw"    # NFS 地址
      device: ":/oj-file"         # 挂载目录