version: "3.4"

services:
  # 注册中心
  eureka:
    image: registry.cn-hangzhou.aliyuncs.com/cloudli/register-center
    networks:
      - oj-net
    ports:
      - "8761:8761"

  # 服务监控
  monitor_service:
    image: registry.cn-hangzhou.aliyuncs.com/cloudli/monitor-service
    networks:
      - oj-net
    ports:
      - "5000:5000"
    environment:
      EUREKA_SERVER: "eureka:8761"

  # 路由网关
  api_gateway:
    image: registry.cn-hangzhou.aliyuncs.com/cloudli/api-gateway
    networks:
      - oj-net
    ports:
      - "80:80"
    environment:
      EUREKA_SERVER: "eureka:8761"
      MYSQL_URL: "jdbc:mysql://mysql:3306/cloud_oj"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "cloud"
      DB_POOL_SIZE: 12

  # Web
  oj_web:
    image: registry.cn-hangzhou.aliyuncs.com/cloudli/cloud-oj-web
    networks:
      - oj-net
    environment:
      EUREKA_SERVER: "eureka:8761"
      GATEWAY_HOST: "192.168.1.20"

  # 管理服务
  manager_service:
    image: registry.cn-hangzhou.aliyuncs.com/cloudli/manager-service
    networks:
      - oj-net
    environment:
      EUREKA_SERVER: "eureka:8761"
      MYSQL_URL: "jdbc:mysql://mysql:3306/cloud_oj?allowMultiQueries=true"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "cloud"
      DB_POOL_SIZE: 12

  # 文件服务
  file_server:
    image: registry.cn-hangzhou.aliyuncs.com/cloudli/file-server
    networks:
      - oj-net
    volumes:
      - "test_data:/test_data"     # 挂载测试数据目录
    environment:
      EUREKA_SERVER: "eureka:8761"

  # 判题服务
  judge_service:
    image: registry.cn-hangzhou.aliyuncs.com/cloudli/judge-service
    networks:
      - oj-net
    volumes:
      - "test_data:/test_data"
      - "target:/target"           # 挂载可执行文件目录（非必须）
    environment:
      EUREKA_SERVER: "eureka:8761"
      MYSQL_URL: "jdbc:mysql://mysql:3306/cloud_oj"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "cloud"
      DB_POOL_SIZE: 12
      RABBIT_URL: "rabbitmq"
      RABBIT_PORT: "5672"
      RABBIT_USER: "cloud@oj"
      RABBIT_PASSWORD: "cloud@oj"
      CORE_POOL_SIZE: 24
      MAX_POOL_SIZE: 24
      QUEUE_CAPACITY: 500

  # 数据库
  mysql:
    image: mysql:8.0.18
    networks:
      - oj-net
    ports:
      - "3306:3306"
    volumes:
      - "./mysql-database/config:/etc/mysql/conf.d"
      - "./mysql-database/initdb:/docker-entrypoint-initdb.d"
      - "mysql:/var/lib/mysql"    # 数据目录
    environment:
      MYSQL_ROOT_PASSWORD: "cloud"
      MYSQL_ROOT_HOST: "%"

  # 消息队列
  rabbitmq:
    image: rabbitmq:3.8.2-management
    hostname: rabbitmq
    networks:
      - oj-net
    environment:
      RABBITMQ_DEFAULT_USER: "cloud@oj"
      RABBITMQ_DEFAULT_PASS: "cloud@oj"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "rabbit:/var/lib/rabbitmq/mnesia"

networks:
  oj-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.16.0.0/16

volumes:
  mysql:
  rabbit:
  target:
  test_data: