version: "3.7"

services:
  # 注册中心
  eureka:
    image: registry.cn-hangzhou.aliyuncs.com/cloud_oj/register-center:latest
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - oj-net
    ports:
      - "8761:8761"
    volumes:
      - "log:/app/log"

  # 服务监控
  monitor_service:
    image: registry.cn-hangzhou.aliyuncs.com/cloud_oj/monitor-service:latest
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - oj-net
    ports:
      - "5000:5000"
    volumes:
      - "log:/app/log"
    environment:
      EUREKA_SERVER: "eureka:8761"

  # 路由网关
  gateway:
    image: registry.cn-hangzhou.aliyuncs.com/cloud_oj/api-gateway:latest
    deploy:
      resources:
        limits:
          memory: 1024M
    networks:
      - oj-net
    volumes:
      - "log:/app/log"
    environment:
      EUREKA_SERVER: "eureka:8761"
      MYSQL_URL: "jdbc:mysql://mysql:3306/cloud_oj?serverTimezone=Asia/Shanghai"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "cloud"
      DB_POOL_SIZE: 12
      TOKEN_VALID_TIME: 4

  # Web
  web:
    image: registry.cn-hangzhou.aliyuncs.com/cloud_oj/web:latest
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - oj-net
    ports: 
      - "80:80"
    environment:
      API_HOST: "gateway"

  # 管理服务
  manager_service:
    image: registry.cn-hangzhou.aliyuncs.com/cloud_oj/manager-service:latest
    deploy:
      resources:
        limits:
          memory: 2048M
    networks:
      - oj-net
    volumes:
      - "log:/app/log"
      - "/var/lib/cloud_oj:/var/lib/cloud_oj"
    environment:
      EUREKA_SERVER: "eureka:8761"
      MYSQL_URL: "jdbc:mysql://mysql:3306/cloud_oj?allowMultiQueries=true&serverTimezone=Asia/Shanghai"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "cloud"
      DB_POOL_SIZE: 12

  # 文件服务
  file_server:
    image: registry.cn-hangzhou.aliyuncs.com/cloud_oj/file-server:latest
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - oj-net
    volumes:
      - "/var/lib/cloud_oj:/var/lib/cloud_oj"
      - "log:/app/log"
    environment:
      EUREKA_SERVER: "eureka:8761"

  # 判题服务
  judge_service:
    image: registry.cn-hangzhou.aliyuncs.com/cloud_oj/judge-service:latest
    deploy:
      resources:
        limits:
          memory: 4096M
    networks:
      - oj-net
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/usr/bin/docker:/usr/bin/docker"
      - "/var/lib/cloud_oj:/var/lib/cloud_oj:ro"
      - "/tmp/code:/tmp/code"
      - "log:/app/log"
    environment:
      EUREKA_SERVER: "eureka:8761"
      MYSQL_URL: "jdbc:mysql://mysql:3306/cloud_oj?serverTimezone=Asia/Shanghai"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "cloud"
      DB_POOL_SIZE: 12
      RABBIT_URL: "rabbitmq"
      RABBIT_PORT: "5672"
      RABBIT_USER: "cloud@oj"
      RABBIT_PASSWORD: "cloud@oj"
      CORE_POOL_SIZE: 8
      MAX_POOL_SIZE: 16
      QUEUE_CAPACITY: 200

  # 数据库
  mysql:
    image: mysql:8.0
    networks:
      - oj-net
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/config:/etc/mysql/conf.d"
      - "./mysql/sql:/docker-entrypoint-initdb.d"
      - "mysql:/var/lib/mysql"
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_ROOT_PASSWORD: "cloud"
      MYSQL_ROOT_HOST: "%"

  # 消息队列
  rabbitmq:
    image: rabbitmq:3.8.2-management
    hostname: rabbitmq
    networks:
      - oj-net
    environment:
      RABBITMQ_DEFAULT_USER: "cloud@oj"
      RABBITMQ_DEFAULT_PASS: "cloud@oj"
    ports:
      - "15672:15672"
    volumes:
      - "rabbit:/var/lib/rabbitmq/mnesia"

networks:
  oj-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.16.0.0/16

volumes:
  mysql:
  rabbit:
  log: